#!/bin/sh
# Generates $2 from $1: a byte array ($3) plus its length ($3_LEN) --
# used to bake a .pl source file into the binary at build time. See the
# Makefile's build/%_pl.h rule for how this is invoked.
set -eu
src="$1"
out="$2"
symbol="$3"

{
    printf '// Generated by Makefile from %s -- do not edit.\n' "$src"
    printf 'static const char %s[] = {' "$symbol"
    od -An -v -tx1 "$src" | tr -s ' ' '\n' | sed '/^$/d' | awk '{ printf "0x%s,", $0; if (NR % 20 == 0) printf "\n    " }'
    printf '\n};\n'
    printf 'static const size_t %s_LEN = sizeof(%s);\n' "$symbol" "$symbol"
} > "$out"
