% te's own default key bindings, leader chords, and named commands --
% generated by hand from what used to be static C tables (BINDINGS,
% PREFIX_BINDINGS, COMMANDS in src/binding.h), now facts like any user
% init.pl could write. Loaded *after* the user's init.pl (see scriptInit in
% script.c), so a user key_binding/3 at the same key/mod as a built-in wins
% -- findall tries clauses in assertion order, and matchAndRun fires on the
% first match.
%
% key_binding/3 checks IsKeyPressed || IsKeyPressedRepeat (fires while held);
% key_binding_once/3 checks IsKeyPressed only (fires once per press) -- the
% same distinction the old Binding struct's `repeat` field made. Nothing
% here needs a custom handler predicate; every one is a direct
% te_action(Name) call, same as a user could write.

% --- leader chords (leader = double-tap Ctrl; Ctrl optional on the chord
% itself, only Shift narrows it -- see modMatchesChord in binding.h) -------

leader_binding(s, any, te_action('save')).
leader_binding(w, any, te_action('save-as')).
leader_binding(o, any, te_action('open')).
leader_binding(a, any, te_action('select-all')).
leader_binding(space, any, te_action('select-line')).
leader_binding(q, any, te_action('quit')).

% --- top-level keys, auto-repeat while held -------------------------------

key_binding(enter, any, te_action('newline')).
key_binding(kp_enter, any, te_action('newline')).
key_binding(tab, any, te_action('indent')).
key_binding(backspace, any, te_action('delete-back')).
key_binding(backspace, ctrl, te_action('delete-forward')).
key_binding(delete, any, te_action('delete-forward')).
key_binding(h, ctrl, te_action('move-left')).
key_binding(l, ctrl, te_action('move-right')).
key_binding(k, ctrl, te_action('move-up')).
key_binding(j, ctrl, te_action('move-down')).
key_binding(a, ctrl, te_action('move-home')).
key_binding(e, ctrl, te_action('move-end')).
key_binding(a, ctrl_shift, te_action('move-buffer-start')).
key_binding(e, ctrl_shift, te_action('move-buffer-end')).
key_binding(w, ctrl, te_action('move-word-start-right')).
key_binding(w, ctrl_shift, te_action('move-word-start-left')).
key_binding(d, ctrl, te_action('move-word-end-right')).
key_binding(h, ctrl_shift, te_action('move-line-left')).
key_binding(l, ctrl_shift, te_action('move-line-right')).
key_binding(j, ctrl_shift, te_action('move-line-down')).
key_binding(k, ctrl_shift, te_action('move-line-up')).
key_binding(f, ctrl, te_action('page-up')).
key_binding(f, ctrl_shift, te_action('page-down')).
key_binding(z, ctrl, te_action('undo')).
key_binding(z, ctrl_shift, te_action('redo')).

% --- top-level keys, fire once per press (holding shouldn't repeat these) -

key_binding_once(c, ctrl, te_action('copy')).
key_binding_once(x, ctrl, te_action('cut')).
key_binding_once(v, ctrl, te_action('paste')).
key_binding_once(x, ctrl_shift, te_action('cut-line')).
key_binding_once(c, ctrl_shift, te_action('copy-line')).
key_binding_once(v, ctrl_shift, te_action('paste-line')).
key_binding_once(s, ctrl, te_action('search')).
key_binding_once(s, ctrl_shift, te_action('search-regex')).
key_binding_once(r, ctrl, te_action('replace')).
key_binding_once(r, ctrl_shift, te_action('replace-regex')).
key_binding_once(q, ctrl, te_action('quit')).

% --- named commands (leader, triple-tap Ctrl, then type the name + Enter) -

command('save', te_action('save')).
command('save-as', te_action('save-as')).
command('open', te_action('open')).
command('search', te_action('search')).
command('search-regex', te_action('search-regex')).
command('search-reverse', te_action('search-reverse')).
command('search-regex-reverse', te_action('search-regex-reverse')).
command('replace', te_action('replace')).
command('replace-regex', te_action('replace-regex')).
command('replace-all', te_action('replace-all')).
command('replace-all-regex', te_action('replace-all-regex')).
command('undo', te_action('undo')).
command('redo', te_action('redo')).
command('copy', te_action('copy')).
command('cut', te_action('cut')).
command('paste', te_action('paste')).
command('select-all', te_action('select-all')).
command('toggle-wrap', te_action('toggle-wrap')).
command('quit', te_action('quit')).
